import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform, Alert } from "react-native";

export async function downloadPasswordPDF(item) {
  try {
    const html = `
      <html><body style="font-family: -apple-system, Roboto, Arial; padding: 24px;">
        <h2>Account: ${item.account}</h2>
        <p><b>Username:</b> ${item.username}</p>
        <p><b>Password:</b> ${item.password}</p>
        <small>Generated by promitsproject</small>
      </body></html>`;
    const { uri } = await Print.printToFileAsync({ html });
    if (Platform.OS === "android" || (await Sharing.isAvailableAsync())) {
      await Sharing.shareAsync(uri);
    } else {
      Alert.alert("Saved", uri);
    }
  } catch (e) {
    Alert.alert("PDF error", e.message);
  }
}
